version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ec2-user/
  - source: src
    destination: /home/ec2-user/src
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300

