#!/bin/bash
#sudo amazon-linux-extras install docker -y
sudo service docker start
#sudo usermod -a -G docker ec2-user
#sudo docker rmi $(docker images -a -q) -f
sudo docker pull nironspot/cicd_rs:blue
#sudo docker tag youngstone89/bluegreen:2.0.0 bluegreen:latest
sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
my_link=/usr/bin/docker-compose
if [ -L ${my_link} ] ; then
   if [ -e ${my_link} ] ; then
      echo "Symlink Exists"
   else
      sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
   fi
elif [ -e ${my_link} ] ; then
   sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
else
   sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
fi
/usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.yml up -d
