#!/bin/bash
sudo service docker start
sudo docker pull nironspot/cicd_rs:green
sudo docker tag nironspot/cicd_rs:green bluegreen:latest
sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
my_link=/usr/bin/docker-compose
if [ -L ${my_link} ] ; then
   if [ -e ${my_link} ] ; then
      echo "Symlink Exists"
   else
      sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
   fi
elif [ -e ${my_link} ] ; then
   sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
else
   sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
fi
